freebsd_instance:
  #image: freebsd-12-1-release-amd64
  image_family: freebsd-12-1-snap

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  pkg_install_script:
  - pkg install -y git-lite
  script:
  - sh util/got-build-regress.sh -b $(git branch --show-current) -f -w $(pwd) emaste@freebsd.org
  check_script:
  - echo === build.log
  - cat build.log || true
  - echo === regress.log
  - cat regress.log || true
  - echo === failures.log
  - cat failures.log || true
  - ls -lR /tmp/got-test-* || true
  - sh core-backtrace.sh
